package com.example.seguritas.screen

import androidx.compose.foundation.layout.*
import androidx.compose.material3.Button
import androidx.compose.material3.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.example.seguritas.utils.PdfUtils
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

@Preview
@Composable
fun PdfScreen() {
    val context = LocalContext.current
    var pdfGenerated by remember { mutableStateOf(false) }

    LaunchedEffect(pdfGenerated) {
        if (pdfGenerated) {
            withContext(Dispatchers.IO) {
                PdfUtils.generateAndSavePdf(context)
            }
        }
    }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(16.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {
        Text(
            "Click below button",
            style = androidx.compose.material3.MaterialTheme.typography.bodyMedium
        )

        Button(onClick = {
            pdfGenerated = true
        }) {
            Text("Generate PDF document")
        }
    }
}




